name: Upload Python Package with Tag Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.12',]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and build package
        run: |
          python -m pip install --upgrade pip
          pip install wheel Cython setuptools
          python setup.py build_ext
      - name: Watch_file
        run: |
          ls
          cd pypynum
          ls
          cd build/lib.*
          ls
          ls pypynum
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-${{ matrix.python-version }}
          path: pypynum/build/**/*.pyd


  create_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          #name: dist-${{ matrix.os }}-${{ matrix.python-version }}
          path: dist/


      - name: 看看文件2
        id: ls_files2
        run: |
          ls;
          echo '\ndist:'
          ls dist 
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: pypynum  # 使用推送的标签名称
          
          body: pypynum打包
          files: dist/**/*
      
