name: Upload Python Package with Tag Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and build package
        run: |
          python -m pip install --upgrade pip
          pip install wheel Cython setuptools
          python setup.py bdist_wheel
      - name: Watch_file
        run: |
        ls
        cd pypynum
        ls
        cd build/lib.*
        ls
        ls pypynum
      - name: fix_linux_wheel
        if: runner.os == 'Linux' && matrix.os == 'ubuntu-latest'
        run: |
          pip install auditwheel
          mkdir distss
          auditwheel repair dist/pypynum-*-*-*-linux_*.whl --plat manylinux_2_35_x86_64 -w ./distss
          ls -lah
          ls dist
          rm -r dist
          mv distss dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-${{ matrix.python-version }}
          path: dist/*.whl
      - name: 看看文件
        id: ls_files
        run: |
          ls;
          echo '\ndist:'
          ls dist
  build_linux:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: write_file
        run: |
          echo hello
          gcc -v
  create_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: create_source_package
        run: |
          python -m pip install -U pip
          pip install -U Cython wheel setuptools
          python setup.py sdist
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          #name: dist-${{ matrix.os }}-${{ matrix.python-version }}
          path: dist/


      - name: 看看文件2
        id: ls_files2
        run: |
          ls;
          echo '\ndist:'
          ls dist 
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: pypynum  # 使用推送的标签名称
          
          body: pypynum打包
          files: dist/**/*
      
